per_listener_settings false

# tunnel-facing: wss://broker.<domain> -> here
listener 8883
protocol websockets
allow_anonymous false

# internal: netmaker server
listener 1883
protocol websockets
allow_anonymous false

password_file /mosquitto/password.txt

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
